### ISSUE TITLE
May I know where I can find the link for the data folder?

### ISSUE THREAD

**Issue by zclecle2** [OSU-BMBL/Spinal-cord-scRNAseq#1]
Hello, 
In your note, you mentioned about a data folder:
You may find a data folder shown in the code. This folder contains processed R object and results. The repository does not provide data/ folder since it is too large (1GB). Please download and unzip it to the repository home folder (download link unavailable due to paper revision).
May I know where I can find the link for the data folder? Many thanks!

**Comment by Wang-Cankun** [comment]
Please download the data folder from here: https://zenodo.org/records/6590561
